inherit_from:
  - https://github.com/jgarber623/rubocop-configs/raw/main/.rubocop.yml
  - https://github.com/jgarber623/rubocop-configs/raw/main/.rubocop-rspec.yml

require:
  - rubocop-packaging

# Checks that the keys, separators, and values of a multi-line hash literal are
# aligned according to configuration.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table

# Checks if examples contain too many `expect` calls.
RSpec/MultipleExpectations:
  Max: 2

# Enforces the use of either `#alias` or `#alias_method`.
Style/Alias:
  EnforcedStyle: prefer_alias_method
